<?= '<h1>'.$this->escapeHtml( $this->category ).'</h1>'; ?>
<table>
    <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Date Created</th>
        <th>Date expires</th>
        <th>City</th>
        <th>Country</th>
    </tr>
<?php foreach ($listings as $item): ?>
    <tr style="background-color:<?php echo $this->cycle(array('#F0F0F0','#FFF'))->next(); ?>" >
        <td>
            <a href="#"><?php echo $item->title; ?></a>
        </td>
        <td>
            <?php echo $item->price; ?>
        </td>
        <td>
            <?php echo date_format(new \DateTime( $item->data_created),'d/m/Y'); ?>
        </td>
        <td>
            <?php echo date_format(new \DateTime( $item->data_expires),'d/m/Y'); ?>
        </td>
        <td>
            <?php echo $item->city; ?>
        </td>
        <td>
            <?php echo $item->country; ?>
        </td>
    </tr>
<?php endforeach; ?>
</table>